[package]
name = "parser-tester"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
ariadne = "0.4"
chumsky = "1.0.0-alpha.7"
flate2 = "1"
winnow = { version = "0.6.20", features = ["debug"] }
